set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets PLL100to8/inst/clk_in1_pll_8MHz]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clock_i_IBUF]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lower_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_upper_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adaptive_mode_i]
set_property IOSTANDARD LVCMOS33 [get_ports amp_sdn_o]
set_property IOSTANDARD LVCMOS33 [get_ports analog_trigger_o]
set_property IOSTANDARD LVCMOS33 [get_ports clock_i]
set_property IOSTANDARD LVCMOS33 [get_ports comp_lower_i]
set_property IOSTANDARD LVCMOS33 [get_ports comp_upper_i]
set_property IOSTANDARD LVCMOS33 [get_ports control_mode_i]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clr_o]
set_property IOSTANDARD LVCMOS33 [get_ports dac_pd_o]
set_property IOSTANDARD LVCMOS33 [get_ports dac_wr_lower_o]
set_property IOSTANDARD LVCMOS33 [get_ports dac_wr_upper_o]
set_property IOSTANDARD LVCMOS33 [get_ports ecg_led_o]
set_property IOSTANDARD LVCMOS33 [get_ports ecg_lod_n_i]
set_property IOSTANDARD LVCMOS33 [get_ports ecg_lod_p_i]
set_property IOSTANDARD LVCMOS33 [get_ports idle_led_o]
set_property IOSTANDARD LVCMOS33 [get_ports overflow_led_o]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_i]
set_property IOSTANDARD LVCMOS33 [get_ports sc_noc_1_o]
set_property IOSTANDARD LVCMOS33 [get_ports sc_noc_2_o]
set_property IOSTANDARD LVCMOS33 [get_ports select_tbs_delta_steps_i]
set_property IOSTANDARD LVCMOS33 [get_ports signal_select_en_o]
set_property IOSTANDARD LVCMOS33 [get_ports signal_select_in_o]
set_property IOSTANDARD LVCMOS33 [get_ports trigger_start_mode_i]
set_property IOSTANDARD LVCMOS33 [get_ports trigger_start_sampling_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports underflow_led_o]

set_property PACKAGE_PIN L5 [get_ports clock_i]

set_property PACKAGE_PIN F3 [get_ports idle_led_o]
set_property PACKAGE_PIN F4 [get_ports overflow_led_o]
set_property PACKAGE_PIN H3 [get_ports underflow_led_o]
set_property PACKAGE_PIN J3 [get_ports ecg_led_o]
set_property PACKAGE_PIN B2 [get_ports trigger_start_mode_i]


set_property PACKAGE_PIN C5 [get_ports {dac_lower_o[0]}]
set_property PACKAGE_PIN D10 [get_ports {dac_lower_o[1]}]
set_property PACKAGE_PIN E4 [get_ports {dac_lower_o[2]}]
set_property PACKAGE_PIN D13 [get_ports {dac_lower_o[3]}]
set_property PACKAGE_PIN C3 [get_ports {dac_lower_o[4]}]
set_property PACKAGE_PIN F13 [get_ports {dac_lower_o[5]}]
set_property PACKAGE_PIN B1 [get_ports {dac_lower_o[6]}]
set_property PACKAGE_PIN G14 [get_ports {dac_lower_o[7]}]
set_property PACKAGE_PIN F12 [get_ports {dac_lower_o[8]}]
set_property PACKAGE_PIN D1 [get_ports {dac_lower_o[9]}]

set_property PACKAGE_PIN G4 [get_ports {dac_upper_o[0]}]
set_property PACKAGE_PIN J14 [get_ports {dac_upper_o[1]}]
set_property PACKAGE_PIN L13 [get_ports {dac_upper_o[2]}]
set_property PACKAGE_PIN M13 [get_ports {dac_upper_o[3]}]
set_property PACKAGE_PIN J11 [get_ports {dac_upper_o[4]}]
set_property PACKAGE_PIN N14 [get_ports {dac_upper_o[5]}]
set_property PACKAGE_PIN K11 [get_ports {dac_upper_o[6]}]
set_property PACKAGE_PIN M5 [get_ports {dac_upper_o[7]}]
set_property PACKAGE_PIN K12 [get_ports {dac_upper_o[8]}]
set_property PACKAGE_PIN M11 [get_ports {dac_upper_o[9]}]

set_property PACKAGE_PIN M12 [get_ports amp_sdn_o]
set_property PACKAGE_PIN E2 [get_ports comp_lower_i]
set_property PACKAGE_PIN G11 [get_ports comp_upper_i]
set_property PACKAGE_PIN J12 [get_ports ecg_lod_n_i]
set_property PACKAGE_PIN M14 [get_ports ecg_lod_p_i]
set_property PACKAGE_PIN B3 [get_ports signal_select_en_o]
set_property PACKAGE_PIN C12 [get_ports signal_select_in_o]
set_property PACKAGE_PIN K4 [get_ports trigger_start_sampling_i]
set_property PACKAGE_PIN J4 [get_ports uart_rx_i]
set_property PACKAGE_PIN F2 [get_ports dac_clr_o]
set_property PACKAGE_PIN H11 [get_ports dac_pd_o]
set_property PACKAGE_PIN G1 [get_ports dac_wr_upper_o]
set_property PACKAGE_PIN H14 [get_ports dac_wr_lower_o]
set_property PACKAGE_PIN A2 [get_ports reset_n_i]
set_property PACKAGE_PIN F14 [get_ports sc_noc_1_o]
set_property PACKAGE_PIN F11 [get_ports sc_noc_2_o]
set_property PACKAGE_PIN H12 [get_ports analog_trigger_o]

set_property PACKAGE_PIN H4 [get_ports uart_tx_o]

set_property PACKAGE_PIN D2 [get_ports control_mode_i]
set_property PACKAGE_PIN C1 [get_ports adaptive_mode_i]
set_property PACKAGE_PIN F1 [get_ports select_tbs_delta_steps_i]

set_property IOSTANDARD LVCMOS33 [get_ports dac_pwm_lower_o]
set_property IOSTANDARD LVCMOS33 [get_ports dac_pwm_upper_o]
set_property PACKAGE_PIN L3 [get_ports dac_pwm_upper_o]
set_property PACKAGE_PIN M3 [get_ports dac_pwm_lower_o]